# vscode extension REST Client

POST http://localhost:8000 HTTP/1.1
content-type: application/json

{
    "orderedAt":"2019-11-09T21:21:46+00:00",
    "customerName":"Tom Jerry 2",
    "items":[
        {
            "itemCode":"123",
            "description":"IPhone 10X3",
            "quantity":1
        },
        {
            "itemCode":"123",
            "description":"IPhone 10X3",
            "quantity":1
        }
    ]
}

###

GET http://localhost:8000/orders HTTP/1.1
content-type: application/json

###

PUT http://localhost:8000/orders HTTP/1.1
content-type: application/json

{
    "orderId": 2,
    "orderedAt":"2019-11-09T21:21:46Z",
    "customerName":"Spike Tyke 2 asdas",
    "items":[
        {
            "itemId": 4,
            "itemCode":"123",
            "description":"IPhone 10X233 asdas 4",
            "quantity": 10
        }
    ]
}

###

DELETE http://localhost:8000/orders/1 HTTP/1.1
content-type: application/json