basePath: /
definitions:
  main.Item:
    properties:
      description:
        example: test Description
        type: string
      item_id:
        example: 1
        type: integer
      quantity:
        example: 1
        type: integer
    type: object
  main.Order:
    properties:
      customerName:
        example: test Customer
        type: string
      items:
        items:
          $ref: '#/definitions/main.Item'
        type: array
      order_id:
        example: 1
        type: integer
      orderedAt:
        example: "2021-09-16T12:51:56.558Z"
        type: string
    type: object
  main.OrderResponsePost:
    properties:
      id:
        example: 1
        type: integer
    type: object
host: localhost:8000
info:
  contact:
    email: test@test.io
    name: API Support
    url: http://www.swagger.io/support
  description: this is sample api for orders
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Orders API
  version: "1.0"
paths:
  /orders:
    get:
      consumes:
      - application/json
      description: get all of orders
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Order'
            type: array
      summary: get all orders
      tags:
      - orders
    post:
      consumes:
      - application/json
      description: create order
      parameters:
      - description: Create Order
        in: body
        name: order
        required: true
        schema:
          $ref: '#/definitions/main.Order'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.OrderResponsePost'
      summary: create order
      tags:
      - orders
swagger: "2.0"
